require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/disbursements", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Disbursement. As you add validations to Disbursement, be sure to
  # adjust the attributes here as well.
  let(:merchant) { create(:merchant) }

  let(:valid_attributes) {
    {
      amount_payable: 100.0,
      merchant_id: merchant.id
    }
  }

  let(:invalid_attributes) {
    {
      amount_payable: nil,
      merchant_id: merchant.id
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # DisbursementsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Disbursement.create! valid_attributes
      get disbursements_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      disbursement = Disbursement.create! valid_attributes
      get disbursement_url(disbursement), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Disbursement" do
        expect {
          post disbursements_url,
               params: { disbursement: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Disbursement, :count).by(1)
      end

      it "renders a JSON response with the new disbursement" do
        post disbursements_url,
             params: { disbursement: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Disbursement" do
        expect {
          post disbursements_url,
               params: { disbursement: invalid_attributes }, as: :json
        }.to change(Disbursement, :count).by(0)
      end

      it "renders a JSON response with errors for the new disbursement" do
        post disbursements_url,
             params: { disbursement: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          amount_payable: 120.0,
          merchant_id: merchant.id
        }
      }

      it "updates the requested disbursement" do
        disbursement = Disbursement.create! valid_attributes
        patch disbursement_url(disbursement),
              params: { disbursement: new_attributes }, headers: valid_headers, as: :json
        disbursement.reload
        expect(disbursement.amount_payable).to eq new_attributes[:amount_payable]
      end

      it "renders a JSON response with the disbursement" do
        disbursement = Disbursement.create! valid_attributes
        patch disbursement_url(disbursement),
              params: { disbursement: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the disbursement" do
        disbursement = Disbursement.create! valid_attributes
        patch disbursement_url(disbursement),
              params: { disbursement: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested disbursement" do
      disbursement = Disbursement.create! valid_attributes
      expect {
        delete disbursement_url(disbursement), headers: valid_headers, as: :json
      }.to change(Disbursement, :count).by(-1)
    end
  end
end
