require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/shoppers", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Shopper. As you add validations to Shopper, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: 'alex',
      email: 'alex@mail.com',
      nif: '7987979'
    }
  }

  let(:invalid_attributes) {
    {
      name: nil,
      email: 'alex@mail.com',
      nif: '7987979'
    }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # ShoppersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Shopper.create! valid_attributes
      get shoppers_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      shopper = Shopper.create! valid_attributes
      get shopper_url(shopper), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Shopper" do
        expect {
          post shoppers_url,
               params: { shopper: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Shopper, :count).by(1)
      end

      it "renders a JSON response with the new shopper" do
        post shoppers_url,
             params: { shopper: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Shopper" do
        expect {
          post shoppers_url,
               params: { shopper: invalid_attributes }, as: :json
        }.to change(Shopper, :count).by(0)
      end

      it "renders a JSON response with errors for the new shopper" do
        post shoppers_url,
             params: { shopper: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          name: 'jon'
        }
      }

      it "updates the requested shopper" do
        shopper = Shopper.create! valid_attributes
        patch shopper_url(shopper),
              params: { shopper: new_attributes }, headers: valid_headers, as: :json
        shopper.reload
        expect(shopper.name).to eq new_attributes[:name]
      end

      it "renders a JSON response with the shopper" do
        shopper = Shopper.create! valid_attributes
        patch shopper_url(shopper),
              params: { shopper: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the shopper" do
        shopper = Shopper.create! valid_attributes
        patch shopper_url(shopper),
              params: { shopper: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested shopper" do
      shopper = Shopper.create! valid_attributes
      expect {
        delete shopper_url(shopper), headers: valid_headers, as: :json
      }.to change(Shopper, :count).by(-1)
    end
  end
end
